# Generated by Django 5.0.4 on 2024-08-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
